import '../matchers';
import { exampleSongSymbol } from '../fixtures/song';
import PdfFormatter from '../../src/formatter/pdf_formatter';
import defaultConfiguration from '../../src/formatter/pdf_formatter/default_configuration';
import StubbedPdfDoc from './stubbed_pdf_doc';
import Configuration from '../../src/formatter/configuration/configuration';

describe('PdfFormatter', () => {
  it('correctly formats a basic song', () => {
    const formatter = new PdfFormatter();
    const config = new Configuration();
    formatter.format(exampleSongSymbol, config, defaultConfiguration, StubbedPdfDoc);
    const doc = formatter.doc as StubbedPdfDoc;

    expect(doc).toHaveText('Let it be', 45, 50);
    expect(doc).toHaveText('Key of C - BPM  - Time', 45, 63);
    expect(doc).toHaveText('By  ChordSheetJS example version', 45, 73);
    expect(doc).toHaveText('Written by: ', 45, 95);
    expect(doc).toHaveText('Verse 1', 45, 119);
    expect(doc).toHaveText('Let it ', 45, 144);
    expect(doc).toHaveText('Am', 69, 133);
    expect(doc).toHaveText('be,', 69, 144);
    expect(doc).toHaveText(' ', 83, 144);
    expect(doc).toHaveText(' ', 85, 144);
    expect(doc).toHaveText('let it ', 88, 144);
    expect(doc).toHaveText('C/G', 108, 133);
    expect(doc).toHaveText('be,', 108, 144);
    expect(doc).toHaveText(' ', 129, 144);
    expect(doc).toHaveText('let it ', 131, 144);
    expect(doc).toHaveText('F', 152, 133);
    expect(doc).toHaveText('be,', 152, 144);
    expect(doc).toHaveText(' ', 164, 144);
    expect(doc).toHaveText('let it ', 166, 144);
    expect(doc).toHaveText('C', 187, 133);
    expect(doc).toHaveText('be', 187, 144);
    expect(doc).toHaveText('D', 45, 158);
    expect(doc).toHaveText('Whisper ', 45, 169);
    expect(doc).toHaveText('words of ', 81, 169);
    expect(doc).toHaveText('G', 119, 158);
    expect(doc).toHaveText('wis', 119, 169);
    expect(doc).toHaveText('A', 133, 158);
    expect(doc).toHaveText('dom,', 133, 169);
    expect(doc).toHaveText(' ', 153, 169);
    expect(doc).toHaveText('let it ', 156, 169);
    expect(doc).toHaveText('G', 176, 158);
    expect(doc).toHaveText('be ', 176, 169);
    expect(doc).toHaveText('D/F#', 188, 158);
    expect(doc).toHaveText('Em', 212, 158);
    expect(doc).toHaveText('D', 230, 158);
    expect(doc).toHaveText('Breakdown', 45, 193);
    expect(doc).toHaveText('Em', 45, 207);
    expect(doc).toHaveText('Whisper words of ', 45, 218);
    expect(doc).toHaveText('F', 119, 207);
    expect(doc).toHaveText('wisdom,', 119, 218);
    expect(doc).toHaveText(' ', 153, 218);
    expect(doc).toHaveText('let it ', 156, 218);
    expect(doc).toHaveText('C', 176, 207);
    expect(doc).toHaveText('be ', 176, 218);
    expect(doc).toHaveText('G', 188, 207);
    expect(doc).toHaveText('Tab 1', 45, 242);
    expect(doc).toHaveText('ABC 1', 45, 274);
    expect(doc).toHaveText('LY 1', 45, 306);
    expect(doc).toHaveText('Bridge 1', 45, 338);
    expect(doc).toHaveText('Bridge line', 45, 352);
    expect(doc).toHaveText('Grid 1', 45, 376);
    expect(doc).toHaveText('©2024 My Music Publishing', 45, 752);
  });
});
