import '../matchers';
import { exampleSongSymbol } from '../fixtures/song';
import PdfFormatter from '../../src/formatter/pdf_formatter';
import defaultConfiguration from '../../src/formatter/pdf_formatter/default_configuration';
import StubbedPdfDoc from './stubbed_pdf_doc';
import { configure } from '../../src/formatter/configuration';

describe('PdfFormatter', () => {
  it('correctly formats a basic song', () => {
    const formatter = new PdfFormatter();
    const config = configure({});
    formatter.format(exampleSongSymbol, config, defaultConfiguration, StubbedPdfDoc);
    const doc = formatter.doc as StubbedPdfDoc;

    expect(doc).toHaveText('Written by: ', 45, 95);
    expect(doc).toHaveText('Verse 1', 45, 119);
    expect(doc).toHaveText('Let it ', 45, 144);
    expect(doc).toHaveText('Am', 69, 133);
    expect(doc).toHaveText('be,', 69, 144);
    expect(doc).toHaveText(' ', 84, 144);
    expect(doc).toHaveText(' ', 87, 144);
    expect(doc).toHaveText('let it ', 90, 144);
    expect(doc).toHaveText('C/G', 111, 133);
    expect(doc).toHaveText('be,', 111, 144);
    expect(doc).toHaveText(' ', 132, 144);
    expect(doc).toHaveText('let it ', 134, 144);
    expect(doc).toHaveText('F', 156, 133);
    expect(doc).toHaveText('be,', 156, 144);
    expect(doc).toHaveText(' ', 169, 144);
    expect(doc).toHaveText('let it ', 172, 144);
    expect(doc).toHaveText('C', 193, 133);
    expect(doc).toHaveText('be', 193, 144);
    expect(doc).toHaveText('D', 45, 158);
    expect(doc).toHaveText('Whisper ', 45, 169);
    expect(doc).toHaveText('words of ', 84, 169);
    expect(doc).toHaveText('G', 125, 158);
    expect(doc).toHaveText('wis', 125, 169);
    expect(doc).toHaveText('A', 139, 158);
    expect(doc).toHaveText('dom,', 139, 169);
    expect(doc).toHaveText(' ', 162, 169);
    expect(doc).toHaveText('let it ', 164, 169);
    expect(doc).toHaveText('G', 186, 158);
    expect(doc).toHaveText('be ', 186, 169);
    expect(doc).toHaveText('D/F#', 199, 158);
    expect(doc).toHaveText('Em', 224, 158);
    expect(doc).toHaveText('D', 243, 158);
    expect(doc).toHaveText('Breakdown', 45, 193);
    expect(doc).toHaveText('Em', 45, 207);
    expect(doc).toHaveText('Whisper words of ', 45, 218);
    expect(doc).toHaveText('F', 125, 207);
    expect(doc).toHaveText('wisdom,', 125, 218);
    expect(doc).toHaveText(' ', 162, 218);
    expect(doc).toHaveText('let it ', 164, 218);
    expect(doc).toHaveText('C', 186, 207);
    expect(doc).toHaveText('be ', 186, 218);
    expect(doc).toHaveText('G', 199, 207);
    expect(doc).toHaveText('Chorus 2', 45, 242);
    expect(doc).toHaveText('G', 45, 256);
    expect(doc).toHaveText('Whisper words of ', 45, 267);
    expect(doc).toHaveText('F', 125, 256);
    expect(doc).toHaveText('wisdom,', 125, 267);
    expect(doc).toHaveText(' ', 162, 267);
    expect(doc).toHaveText('let it ', 164, 267);
    expect(doc).toHaveText('C', 186, 256);
    expect(doc).toHaveText('be ', 186, 267);
    expect(doc).toHaveText('G', 199, 256);
    expect(doc).toHaveText('Solo 1', 45, 291);
    expect(doc).toHaveText('G', 45, 305);
    expect(doc).toHaveText('Solo line 1', 45, 316);
    expect(doc).toHaveText('C', 45, 330);
    expect(doc).toHaveText('Solo line 2', 45, 341);
    expect(doc).toHaveText('Tab 1', 45, 365);
  });
});
