name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Enable Corepack
        run: corepack enable
      - name: Build
        run: yarn install && yarn build:release
      - name: Test
        run: cat lib/bundle.js
      - name: Create release
        run: gh release create "$tag" --title="v${tag#v}" --generate-notes
      - name: Upload release assets
        run: gh release upload "$tag" lib/bundle.js lib/bundle.min.js
      - name: Generate typedoc
        run: yarn typedoc
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: tmp/docs

  typedoc:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
